apiVersion: v1
kind: ServiceAccount
metadata:
  name: podbump
  namespace: podbump
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podbump
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "watch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podbump
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: podbump
subjects:
- kind: ServiceAccount
  name: podbump
  namespace: podbump